COMPILER = gcc
C_FLAGS = -m32 -c -ffreestanding

LINKER = ld
L_FLAGS = -m elf_i386 -T linker.ld

ASSEMBLER = nasm
A_FLAGS = -f elf32

EMULATOR = qemu-system-i386
EMULATOR_FLAGS = -kernel

OUTPUT = obj/kernel/kernel.bin
SRC = src
OBJ = obj
